site_name: garnet技术笔记
nav:
  - 喵喵之家: index.md
  - test:ww.md
  #    - test: test/test.md
 



markdown_extensions:
  - attr_list
  - md_in_html  # https://squidfunk.github.io/mkdocs-material/reference/images/
  - markdown.extensions.codehilite
  - markdown.extensions.extra
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.tables
  - toc:
      permalink: true       # 在每个标题旁添加链接
      toc_depth: 1-6

plugins:
  - mkdocs-pdf
  - search


theme:
  # name: readthedocs
  name: material
  # custom_dir: overrides
  palette:
    primary: 'indigo'       # 主颜色
    accent: 'pink'          # 强调颜色
  font:
    text: 'Roboto'          # 主文字字体
    code: 'Roboto Mono'     # 代码块字体
  features:
    - navigation.indexes    # 对于包含子页面的节，提供更好的索引页面
    - navigation.instant
    - navigation.path       # 在文档顶部也显示当前文档的 
    - navigation.top
    - navigation.tabs
    - palette.switcher      # 主题色切换
    - search.suggest        # 搜索建议
    - search.highlight      # 搜索关键词高亮
    - instant.loading       # 启用页面的即时加载
    - navigation.footer



extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  # - javascripts/extra.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js





